# Generated by Django 3.2.8 on 2021-10-15 16:02

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='category')),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Home_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة الرئيسية الاولى')),
                ('image_2', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة الرئيسية الثانيه')),
                ('image_3', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='الصورة الرئيسية الثالثة')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(db_index=True, max_length=100, verbose_name='أسم المنتج ')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('descrip', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج')),
                ('product_info', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='معلومات المنتج')),
                ('Book_image', models.ImageField(blank=True, null=True, upload_to='Produkten/', verbose_name='صور')),
                ('price', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='سعر المنتج')),
                ('Discountprice', models.DecimalField(decimal_places=0, default='0', max_digits=7, verbose_name='سعر عند وجود خصم')),
                ('Frakt', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Frakt')),
                ('created', models.DateTimeField(verbose_name='تاريخ الاضافة')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ الاضافة')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bock.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProImag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='0', upload_to='Produkten/', verbose_name='produktbild')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bock.product', verbose_name='produktnamn')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bock.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
