# Generated by Django 3.2.8 on 2021-10-15 16:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(db_index=True, max_length=200, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='Book_name_ar',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج '),
        ),
        migrations.AddField(
            model_name='product',
            name='Book_name_en',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج '),
        ),
        migrations.AddField(
            model_name='product',
            name='Book_name_sv',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج '),
        ),
        migrations.AddField(
            model_name='product',
            name='Book_name_tr',
            field=models.CharField(db_index=True, max_length=100, null=True, verbose_name='أسم المنتج '),
        ),
        migrations.AddField(
            model_name='product',
            name='descrip_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='descrip_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='descrip_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='descrip_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='وصف المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info_ar',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='معلومات المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='معلومات المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info_sv',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='معلومات المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info_tr',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', null=True, verbose_name='معلومات المنتج'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='bock.category'),
        ),
    ]
